const $ = (id) => document.getElementById(id);
const TYPE_LABELS = {text:'Texto',textarea:'Parágrafo',number:'Número',date:'Data',select:'Lista de opções',checkbox:'Caixa de seleção',email:'E-mail',phone:'Telefone',url:'Link'};
const ROLE_LABELS = {id:'Identificador único',name:'Nome do contato',phone:'Telefone',stage:'Etapa do funil',nextContact:'Próximo contato',notes:'Anotações'};
const VIEW_INFO = {contacts:['Contatos','Seus contatos, por perto.','Organize cada conversa com os campos que fazem sentido para você.'],pipeline:['Funil','Cada relação tem seu próximo passo.','Acompanhe seus contatos pelas etapas que você definiu.'],followups:['Acompanhamentos','Um bom momento para retomar.','Contatos com acompanhamento marcado até hoje.'],templates:['Modelos de mensagem','Suas palavras, mais acessíveis.','Prepare textos, personalize e revise antes de enviar.'],settings:['Configurações','Um CRM do seu jeito.','Escolha sua fonte de dados e personalize cada campo.']};
let state = null, view = 'contacts', editing = null, draftFields = [], noticeTimer;
function el(tag, props = {}, children = []) { const e = document.createElement(tag); for (const [key,value] of Object.entries(props)) { if (key === 'text') e.textContent = value; else if (key === 'class') e.className = value; else if (key.startsWith('on')) e.addEventListener(key.slice(2),value); else if (key in e) e[key] = value; else e.setAttribute(key,value); } for(const child of children)e.append(child);return e; }
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function nameOf(r) { return String(r.values[state.config.roles.name] || 'Sem nome'); }
function roleValue(r,role) { return String(r.values[state.config.roles[role]] ?? ''); }
function due(r) { const v = roleValue(r,'nextContact'); return /^\d{4}-\d{2}-\d{2}$/.test(v) && v <= today(); }
function notice(message,error=false) { clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').className='notice'+(error?' error':'');$('notice').hidden=false;if(!error)noticeTimer=setTimeout(()=>$('notice').hidden=true,6000); }
async function rpc(type,payload={}) { const scoped=['CONTACT_SAVE','CONTACT_DELETE','SCHEMA_SAVE','CONFIG_SAVE','LINK_CHAT','IMPORT_BACKUP','CLEAR_LOCAL_DATA','INITIALIZE_IDS'];if(state&&scoped.includes(type))payload={...payload,scope:state.config.provider==='sheets'?`sheets:${state.config.spreadsheetId}:${state.config.sheetId??'unselected'}`:'local'};const response = await chrome.runtime.sendMessage({type,payload}); if(!response?.ok)throw new Error(response?.error?.message || 'A extensão não respondeu. Recarregue a página e tente novamente.');return response.data; }
async function refresh() { state=await rpc('STATE');draftFields=structuredClone(state.fields);render(); }
async function action(type,payload={},message='Alteração salva.') { const result=await rpc(type,payload);await refresh();if(message)notice(message);return result; }
async function safely(fn) { try { await fn(); } catch(error){notice(error.message,true);} }
function options(select,entries,value='') { select.replaceChildren(...entries.map(([v,label])=>el('option',{value:v,text:label})));select.value=value; }
function showView(next) { view=VIEW_INFO[next]?next:'contacts'; for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.view===view);const [crumb,title,description]=VIEW_INFO[view];$('breadcrumb').textContent=crumb;$('page-title').textContent=title;$('page-description').textContent=description;$('data-view').hidden=['settings','templates'].includes(view);$('templates-view').hidden=view!=='templates';$('settings-view').hidden=view!=='settings';$('metrics').hidden=['settings','templates'].includes(view);$('new-contact').hidden=['settings','templates'].includes(view);render(); }
function render() { if(!state)return;$('connection').textContent=state.config.provider==='sheets'?'Google Sheets':'Dados neste navegador';$('new-contact').disabled=state.connection?.writable===false;$('empty-new').disabled=state.connection?.writable===false;if(state.connection?.issue)notice(state.connection.issue.message,true);$('metric-total').textContent=state.records.length;$('metric-due').textContent=state.records.filter(due).length;const stages=stageOptions();$('metric-stages').textContent=stages.length;const chosen=$('stage-filter').value;options($('stage-filter'),[['','Todas as etapas'],...stages.map(s=>[s,s])],chosen);if(view==='settings')renderSettings();else if(view==='templates')renderTemplates();else renderRecords(); }
function stageOptions() { const key=state.config.roles.stage;const field=state.fields.find(f=>f.key===key);return [...new Set([...(field?.options||[]),...state.records.map(r=>roleValue(r,'stage')).filter(Boolean)])]; }
function filteredRecords() { const q=$('search').value.trim().toLocaleLowerCase();const stage=view==='followups'?'':$('stage-filter').value;return state.records.filter(r=>(!q||Object.values(r.values).some(v=>String(v??'').toLocaleLowerCase().includes(q)))&&(!stage||roleValue(r,'stage')===stage)&&(view!=='followups'||due(r))); }
function avatar(name) { return name.split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('').toUpperCase(); }
function displayDate(value) { if(!value)return 'Sem data';if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value.split('-').reverse().join('/');return value; }
function renderRecords() { const records=filteredRecords();$('list').replaceChildren();$('empty').hidden=state.records.length>0;$('stage-filter').hidden=view==='followups';if(!state.records.length)return;if(!records.length){$('list').append(el('div',{class:'empty',text:view==='followups'?'Nenhum acompanhamento vencido. Sua agenda está em dia.':'Nenhum contato encontrado para este filtro.'}));return;}if(view==='pipeline'){renderPipeline(records);return;}const table=el('table'),thead=el('thead'),tr=el('tr');for(const title of ['Contato','Telefone','Etapa','Próximo contato',''])tr.append(el('th',{text:title}));thead.append(tr);table.append(thead);const tbody=el('tbody');for(const r of records){const row=el('tr',{'data-record':r.id});const n=nameOf(r);const contact=el('div',{class:'contact-cell'},[el('span',{class:'avatar',text:avatar(n)}),el('div',{},[el('div',{class:'contact-name',text:n}),el('div',{class:'contact-sub',text:r.values[state.fields.find(f=>f.type==='email'&&!f.hidden)?.key]||r.values.empresa||'Contato'})])]);const open=el('button',{class:'record-link',text:'Abrir ficha',onclick:()=>openContact(r)});row.addEventListener('dblclick',()=>openContact(r));row.append(el('td',{},[contact]),el('td',{text:roleValue(r,'phone')||'—'}),el('td',{},[el('span',{class:'stage-pill',text:roleValue(r,'stage')||'Sem etapa'})]),el('td',{class:due(r)?'due':'',text:displayDate(roleValue(r,'nextContact'))}),el('td',{},[open]));tbody.append(row);}table.append(tbody);$('list').append(el('div',{class:'table-wrap'},[table])); }
function renderPipeline(records) { const board=el('div',{class:'pipeline'});const stages=[...stageOptions()];if(records.some(r=>!roleValue(r,'stage')))stages.push('Sem etapa');for(const s of stages){const selected=records.filter(r=>(roleValue(r,'stage')||'Sem etapa')===s);const col=el('section',{class:'pipeline-column'},[el('h3',{},[el('span',{text:s}),el('span',{text:selected.length})])]);for(const r of selected){const card=el('div',{class:'pipeline-card'},[el('strong',{text:nameOf(r)}),el('p',{text:roleValue(r,'phone')||'Sem telefone'}),el('p',{class:due(r)?'due':'',text:'Próximo contato · '+displayDate(roleValue(r,'nextContact'))}),el('button',{class:'text-button',text:'Abrir ficha',onclick:()=>openContact(r)})]);col.append(card);}board.append(col);}$('list').append(board); }
function inputFor(field,value) { let input;if(field.type==='select'){input=el('select');options(input,[['','Selecione'],...(field.options||[]).map(v=>[v,v])],String(value??''));if(value&&!field.options?.includes(String(value)))input.append(el('option',{value:String(value),text:String(value),selected:true}));}else if(field.type==='textarea'){input=el('textarea',{rows:4,value:String(value??'')});}else{input=el('input',{type:{phone:'tel',number:'number',date:'date',checkbox:'checkbox',email:'email',url:'url'}[field.type]||'text'});if(field.type==='checkbox')input.checked=value===true||value==='TRUE';else input.value=String(value??'');if(field.type==='number')input.step='any';}input.dataset.key=field.key;input.required=!!field.required&&!field.readOnly;input.disabled=!!field.readOnly||field.key===state.config.roles.id;return input; }
function openContact(record=null) { editing=record?structuredClone(record):null;$('dialog-title').textContent=record?nameOf(record):'Novo contato';$('dialog-error').hidden=true;$('delete-contact').hidden=!record||state.config.provider!=='local';$('save-contact').disabled=state.connection?.writable===false;$('contact-fields').replaceChildren();for(const f of state.fields.filter(f=>(!f.hidden||(!record&&f.required))&&f.key!==state.config.roles.id)){const label=el('label',{class:f.type==='textarea'?'wide':''},[el('span',{text:f.label+(f.required?' *':'')+(f.readOnly?' · somente leitura':'')}),inputFor(f,record?.values[f.key])]);$('contact-fields').append(label);}if(!$('contact-dialog').open)$('contact-dialog').showModal(); }
async function saveContact(event) { event.preventDefault();const values={...(editing?.values||{})};for(const input of $('contact-fields').querySelectorAll('[data-key]')){if(input.disabled)continue;const field=state.fields.find(f=>f.key===input.dataset.key);values[field.key]=field.type==='checkbox'?input.checked:field.type==='number'&&input.value!==''?Number(input.value):input.value;}const button=$('save-contact');button.disabled=true;try{await action('CONTACT_SAVE',{id:editing?.id,values,expected:editing?.values},'Contato salvo.');$('contact-dialog').close();}catch(error){$('dialog-error').textContent=error.message;$('dialog-error').hidden=false;}finally{button.disabled=false;} }
function renderSettings() { $('prepare-ids').hidden=state.config.provider!=='sheets'||state.config.sheetId==null;$('clear-local').hidden=state.config.provider!=='local';$('source-summary').textContent=state.config.provider==='sheets'?`Google Sheets · ${state.config.sheetTitle||state.config.spreadsheetId} · ${state.records.length} contatos`:`Neste navegador · ${state.records.length} contatos`;$('disconnect').hidden=state.config.provider!=='sheets';$('sheet-url').value=state.config.spreadsheetId||'';$('country-code').value=state.config.countryCode||'55';$('roles-list').replaceChildren();for(const [role,label] of Object.entries(ROLE_LABELS)){const select=el('select',{'data-role':role});options(select,[['','Não usar'],...state.fields.map(f=>[f.key,f.label])],state.config.roles[role]||'');if(['id','name'].includes(role))select.required=true;$('roles-list').append(el('label',{text:label},[select]));}renderFields(); }
function renderFields() {
 $('field-list').replaceChildren();
 for(const [i,f] of draftFields.entries()) {
  const label=el('input',{value:f.label,'aria-label':'Rótulo de '+f.key,oninput:e=>f.label=e.target.value});
  const type=el('select',{'aria-label':'Tipo de '+f.key,onchange:e=>{f.type=e.target.value;}});
  options(type,Object.entries(TYPE_LABELS),f.type);
  const choices=el('input',{value:(f.options||[]).join('; '),placeholder:'Opções separadas por ;','aria-label':'Opções de '+f.key,oninput:e=>f.options=e.target.value.split(';').map(v=>v.trim()).filter(Boolean)});
  const flags=el('div',{class:'field-flags'});
  for(const [key,title] of [['hidden','Ocultar'],['required','Obrigatório'],['readOnly','Somente leitura']]) {
   const input=el('input',{type:'checkbox',checked:!!f[key],onchange:e=>f[key]=e.target.checked});
   if(f.key===state.config.roles.id&&key!=='hidden')input.disabled=true;
   flags.append(el('label',{text:title},[input]));
  }
  const row=el('div',{class:'field-row'},[el('code',{text:f.key}),label,type,choices,flags]);
  if(f.key===state.config.roles.id){type.disabled=true;choices.disabled=true;}
  row.dataset.index=i;$('field-list').append(row);
 }
}
async function addField(event) { event.preventDefault();const key=$('field-key').value.trim(),label=$('field-label').value.trim(),type=$('field-type').value;if(draftFields.some(f=>f.key===key)){notice('Essa chave de coluna já existe.',true);return;}if(!/^[\p{L}\p{N}_ -]{1,80}$/u.test(key)){notice('Use letras, números, espaços, hífen ou sublinhado na chave.',true);return;}draftFields.push({key,label,type,options:[],hidden:false});renderFields();$('add-field').reset();notice('Campo adicionado ao rascunho. Clique em Salvar campos para aplicar.'); }
function renderTemplates() { $('template-list').replaceChildren();for(const [i,t] of (state.templates||[]).entries()){const text=t.text||t.body||'';const card=el('article',{class:'template-card'},[el('h3',{text:t.name}),el('p',{text}),el('button',{class:'text-button',text:'Copiar texto',onclick:()=>safely(async()=>{await navigator.clipboard.writeText(text);notice('Texto copiado. Revise e personalize antes de enviar.');})}),el('button',{class:'text-button',text:'Remover',onclick:()=>safely(()=>action('TEMPLATES_SAVE',{templates:state.templates.filter((_,j)=>j!==i)},'Modelo removido.'))})]);$('template-list').append(card);} }
function download(filename,content,type) { const url=URL.createObjectURL(new Blob([content],{type}));const link=el('a',{href:url,download:filename});document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000); }
function csvCell(value) { let s=String(value??'');if(/^(?:\s*[=+@\-＝＋＠－]|[\t\r\n])/u.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'; }
function exportCSV() { const fields=state.fields.filter(f=>!f.hidden);const rows=[fields.map(f=>csvCell(f.key)).join(','),...filteredRecords().map(r=>fields.map(f=>csvCell(r.values[f.key])).join(','))];download('sheetdock-contatos.csv','\uFEFF'+rows.join('\r\n'),'text/csv;charset=utf-8');notice('CSV exportado com os contatos do filtro atual.'); }
function backup() { download('sheetdock-backup.json',JSON.stringify({format:'sheetdock-backup',version:1,exportedAt:new Date().toISOString(),fields:state.fields,roles:state.config.roles,countryCode:state.config.countryCode,records:state.records.map(({id,values})=>({id,values})),templates:state.templates},null,2),'application/json');notice('Backup exportado. Guarde o arquivo em local seguro.'); }
async function importBackup(event) { const file=event.target.files[0];if(!file)return;try{if(state.config.provider!=='local')throw new Error('Use o modo local para importar um backup.');if(file.size>5_000_000)throw new Error('O backup deve ter até 5 MB.');const data=JSON.parse(await file.text());if(data.format!=='sheetdock-backup'||data.version!==1||!Array.isArray(data.records)||!Array.isArray(data.fields)||data.records.length>5000)throw new Error('Backup inválido ou acima de 5.000 registros.');if(!confirm(`Acrescentar ${data.records.length} contatos ao modo local? Seus registros atuais serão preservados.`))return;await action('IMPORT_BACKUP',{backup:data},`${data.records.length} contatos importados com novos identificadores.`);}catch(error){await refresh();notice(error.message,true);}finally{event.target.value='';} }
for(const button of document.querySelectorAll('nav button'))button.addEventListener('click',()=>showView(button.dataset.view));
$('refresh').addEventListener('click',()=>safely(()=>action('REFRESH',{},'Dados atualizados.')));
$('open-wa').addEventListener('click',()=>chrome.tabs.create({url:'https://web.whatsapp.com/'}));
$('new-contact').addEventListener('click',()=>openContact());$('empty-new').addEventListener('click',()=>openContact());$('empty-connect').addEventListener('click',()=>showView('settings'));
$('search').addEventListener('input',()=>renderRecords());$('stage-filter').addEventListener('change',()=>renderRecords());
$('contact-form').addEventListener('submit',saveContact);$('close-dialog').addEventListener('click',()=>$('contact-dialog').close());$('cancel-dialog').addEventListener('click',()=>$('contact-dialog').close());
$('delete-contact').addEventListener('click',()=>safely(async()=>{if(editing&&confirm(`Excluir ${nameOf(editing)} da base local? Esta ação remove também seus vínculos de conversa.`)){await action('CONTACT_DELETE',{id:editing.id,expected:editing.values},'Contato excluído da base local.');$('contact-dialog').close();}}));
$('demo').addEventListener('click',()=>safely(async()=>{if(confirm('Adicionar três contatos fictícios para conhecer o CRM? Nenhum contato real será criado.'))await action('DEMO_RESET',{},'Dados de demonstração adicionados.');}));
$('export').addEventListener('click',exportCSV);$('backup').addEventListener('click',backup);$('import-file').addEventListener('change',importBackup);
$('connect-form').addEventListener('submit',event=>{event.preventDefault();safely(async()=>{const result=await rpc('CONNECT',{spreadsheetUrl:$('sheet-url').value});const tabs=result.tabs||result.sheets||[];options($('sheet-tabs'),tabs.map(t=>[String(t.id??t.sheetId),t.title]));$('tabs-panel').hidden=false;notice('Conta conectada. Escolha a aba para continuar.');});});
$('select-tab').addEventListener('click',()=>safely(async()=>{await action('SELECT_SHEET',{sheetId:Number($('sheet-tabs').value)},'Planilha conectada. Revise os campos principais.');$('tabs-panel').hidden=true;}));
$('create-sheet').addEventListener('click',()=>safely(async()=>{const title=prompt('Nome da nova planilha','Meu CRM');if(title?.trim())await action('CREATE_SHEET',{title:title.trim()},'Planilha modelo criada na sua conta Google.');}));
$('disconnect').addEventListener('click',()=>safely(async()=>{if(confirm('Desconectar o Google e voltar aos dados locais? Sua planilha será preservada.'))await action('DISCONNECT',{},'Google desconectado. Dados locais disponíveis.');}));
$('clear-local').addEventListener('click',()=>safely(async()=>{if(state.config.provider!=='local')throw new Error('Desconecte o Google antes de apagar os dados deste navegador.');if(confirm('Apagar todos os contatos, campos, modelos e configurações salvos neste navegador? Exporte um backup antes. Esta ação não apaga planilhas do Google.'))await action('CLEAR_LOCAL_DATA',{confirmation:'CLEAR_LOCAL_DATA'},'Dados deste navegador apagados.');}));
$('prepare-ids').addEventListener('click',()=>safely(async()=>{if(confirm('Preparar identificadores na planilha? O CRM criará uma coluna de ID se necessário e preencherá somente IDs vazios. Outros dados serão preservados.'))await action('INITIALIZE_IDS',{confirmation:'INITIALIZE_IDS'},'Identificadores preparados. Revise os campos principais.');}));
$('roles-form').addEventListener('submit',event=>{event.preventDefault();safely(async()=>{const roles={};for(const s of $('roles-list').querySelectorAll('[data-role]'))roles[s.dataset.role]=s.value;await rpc('CONFIG_SAVE',{config:{countryCode:$('country-code').value}});await action('SCHEMA_SAVE',{fields:draftFields,roles},'Organização salva.');});});
$('add-field').addEventListener('submit',addField);$('save-fields').addEventListener('click',()=>safely(()=>action('SCHEMA_SAVE',{fields:draftFields,roles:state.config.roles},'Campos salvos.')));
$('template-form').addEventListener('submit',event=>{event.preventDefault();safely(async()=>{const templates=[...(state.templates||[]),{id:crypto.randomUUID(),name:$('template-name').value.trim(),text:$('template-text').value}];await action('TEMPLATES_SAVE',{templates},'Modelo adicionado.');$('template-form').reset();});});
options($('field-type'),Object.entries(TYPE_LABELS),'text');
await safely(refresh);
